### ISSUE TITLE
生成的dll在libloader中验证通不过

### ISSUE THREAD

**Issue by syokanatsu** [Nambers/MiraiCP-template#6]
![image](https://user-images.githubusercontent.com/50983420/179704669-1de62778-61dc-4a6d-84f0-20cc44ef5989.png)
单文件头文件中并没有导出这四个接口，导致libloader验证的时候通不过，会导致加载失败，加上__declspec(dllexport)后通过验证

**Comment by Nambers** [comment]
是的，我们已经发现了这个问题，以及一些其他的问题

https://github.com/Nambers/MiraiCP/issues/119

下个版本会修复
